package com.moodlescraper.logger;

import java.util.logging.Formatter;
import java.util.logging.LogRecord;

/**
 * A formatter for the default logger generated by {@link LoggerFactory}
 * outputs the source class name followed by the message
 * 
 * @author sk902
 */
public class LoggingFormatter extends Formatter {

    @Override
    public String format(LogRecord record) {
        String className = record.getSourceClassName().split("\\.")[record.getSourceClassName().split("\\.").length
                - 1];
        String message = record.getMessage() + "\n";

        // ANSI escape codes for coloring
        String orangeColor = "\u001B[33m"; // Orange color
        String resetColor = "\u001B[0m"; // Reset color

        String formattedMessage = "[" + orangeColor + className + "#" + record.getSourceMethodName() + resetColor + "] " + message;

        return formattedMessage;
    }
}